version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    ignore:
      - dependency-name: "ranacseruet/snapdrift/*"
      - dependency-name: "ranacseruet/snapdrift"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
