/** @jest-environment node */

import { jest } from '@jest/globals';

describe('generateHtmlReport', () => {
  let generateHtmlReport;

  beforeAll(async () => {
    ({ generateHtmlReport } = await import('../src/html-report.mjs'));
  });

  const makeSummary = (overrides = {}) => ({
    startedAt: '2025-01-01T00:00:00.000Z',
    finishedAt: '2025-01-01T00:00:01.000Z',
    status: 'clean',
    selectedRoutes: ['home-desktop', 'home-mobile'],
    baselineResultsPath: '/tmp/baseline-results.json',
    currentResultsPath: '/tmp/current-results.json',
    baselineManifestPath: '/tmp/baseline-manifest.json',
    currentManifestPath: '/tmp/current-manifest.json',
    diffMode: 'report-only',
    threshold: 0.01,
    totalScreenshots: 2,
    matchedScreenshots: 2,
    changedScreenshots: 0,
    missingInBaseline: 0,
    missingInCurrent: 0,
    changed: [],
    missing: [],
    errors: [],
    dimensionChanges: [],
    ...overrides
  });

  it('generates a valid HTML document for a clean summary', async () => {
    const html = await generateHtmlReport(makeSummary());
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<title>SnapDrift Report</title>');
    expect(html).toContain('status-clean');
    expect(html).toContain('&#10003; Clean');
    expect(html).toContain('>Drift signals<');
    expect(html).toContain('>Capture gaps<');
    expect(html).toContain('>Dimension shifts<');
    expect(html).toContain('>Comparison errors<');
  });

  it('shows drift-detected status class and label', async () => {
    const html = await generateHtmlReport(makeSummary({ status: 'changes-detected' }));
    expect(html).toContain('status-changes');
    expect(html).toContain('Drift detected');
  });

  it('shows incomplete status for unknown status', async () => {
    const html = await generateHtmlReport(makeSummary({ status: undefined }));
    expect(html).toContain('status-incomplete');
    expect(html).toContain('Incomplete');
  });

  it('renders stats in header', async () => {
    const html = await generateHtmlReport(makeSummary());
    expect(html).toContain('<strong>0</strong><span>Drift signals</span>');
    expect(html).toContain('<strong>2</strong><span>Stable captures</span>');
  });

  it('renders changed routes with table rows', async () => {
    const html = await generateHtmlReport(makeSummary({
      status: 'changes-detected',
      changedScreenshots: 1,
      changed: [{
        id: 'home-desktop',
        path: '/',
        viewport: 'desktop',
        baselineImagePath: 'baseline.png',
        currentImagePath: 'current.png',
        width: 1440,
        height: 900,
        differentPixels: 500,
        totalPixels: 1296000,
        mismatchRatio: 0.000386,
        status: 'changed'
      }]
    }));
    expect(html).toContain('<td>home-desktop</td>');
    expect(html).toContain('0.04%');
  });

  it('renders capture gaps when missing items exist', async () => {
    const html = await generateHtmlReport(makeSummary({
      status: 'incomplete',
      missingInBaseline: 1,
      missing: [{ id: 'about-desktop', location: 'baseline', reason: 'missing baseline capture' }]
    }));
    expect(html).toContain('<td>about-desktop</td>');
    expect(html).toContain('<td>baseline</td>');
    expect(html).toContain('<td>missing baseline capture</td>');
  });

  it('renders dimension shifts when present', async () => {
    const html = await generateHtmlReport(makeSummary({
      status: 'incomplete',
      dimensionChanges: [{
        id: 'home-desktop',
        viewport: 'desktop',
        baselineWidth: 1440,
        baselineHeight: 1266,
        currentWidth: 1440,
        currentHeight: 1092,
        status: 'dimension-changed'
      }]
    }));
    expect(html).toContain('1440&times;1266');
    expect(html).toContain('1440&times;1092');
  });

  it('renders errors when present', async () => {
    const html = await generateHtmlReport(makeSummary({
      status: 'incomplete',
      errors: [{ id: 'home-desktop', message: 'Navigation timeout' }]
    }));
    expect(html).toContain('<td>home-desktop</td>');
    expect(html).toContain('<td>Navigation timeout</td>');
  });

  it('renders baseline metadata when available', async () => {
    const html = await generateHtmlReport(makeSummary({
      baselineArtifactName: 'my-baseline',
      baselineSourceSha: 'abc1234'
    }));
    expect(html).toContain('Baseline: <code>my-baseline</code>');
    expect(html).toContain('SHA: <code>abc1234</code>');
  });

  it('includes footer with SnapDrift link', async () => {
    const html = await generateHtmlReport(makeSummary());
    expect(html).toContain('Generated by <a href="https://github.com/ranacseruet/snapdrift">SnapDrift</a>');
  });

  describe('without imageReader', () => {
    it('does not embed any images', async () => {
      const html = await generateHtmlReport(makeSummary({
        status: 'changes-detected',
        changedScreenshots: 1,
        changed: [{
          id: 'home-desktop',
          path: '/',
          viewport: 'desktop',
          baselineImagePath: 'baseline.png',
          currentImagePath: 'current.png',
          width: 1440,
          height: 900,
          differentPixels: 500,
          totalPixels: 1296000,
          mismatchRatio: 0.000386,
          status: 'changed'
        }]
      }), { baselineRunDir: '/tmp/run', currentRunDir: '/tmp/run' });
      expect(html).not.toContain('data:image/png;base64,');
      expect(html).not.toContain('Image unavailable');
    });
  });

  describe('with imageReader', () => {
    it('embeds images returned by imageReader', async () => {
      const imageReader = jest.fn().mockResolvedValue('fakeBase64Data');
      const html = await generateHtmlReport(makeSummary({
        status: 'changes-detected',
        changedScreenshots: 1,
        changed: [{
          id: 'home-desktop',
          path: '/',
          viewport: 'desktop',
          baselineImagePath: 'baseline.png',
          currentImagePath: 'current.png',
          width: 1440,
          height: 900,
          differentPixels: 500,
          totalPixels: 1296000,
          mismatchRatio: 0.000386,
          status: 'changed'
        }]
      }), { baselineRunDir: '/tmp/run', currentRunDir: '/tmp/run', imageReader });

      expect(imageReader).toHaveBeenCalledTimes(2);
      expect(imageReader).toHaveBeenCalledWith('/tmp/run', 'baseline.png');
      expect(imageReader).toHaveBeenCalledWith('/tmp/run', 'current.png');
      expect(html).toContain('data:image/png;base64,fakeBase64Data');
    });

    it('shows Image unavailable when imageReader returns null', async () => {
      const imageReader = jest.fn().mockResolvedValue(null);
      const html = await generateHtmlReport(makeSummary({
        status: 'changes-detected',
        changedScreenshots: 1,
        changed: [{
          id: 'home-desktop',
          path: '/',
          viewport: 'desktop',
          baselineImagePath: 'baseline.png',
          currentImagePath: 'current.png',
          width: 1440,
          height: 900,
          differentPixels: 500,
          totalPixels: 1296000,
          mismatchRatio: 0.000386,
          status: 'changed'
        }]
      }), { baselineRunDir: '/tmp/run', currentRunDir: '/tmp/run', imageReader });

      expect(html).toContain('Image unavailable');
      expect(html).not.toContain('data:image/png;base64,');
    });

    it('does not call imageReader when runDirs are absent', async () => {
      const imageReader = jest.fn().mockResolvedValue('fakeBase64Data');
      const html = await generateHtmlReport(makeSummary({
        status: 'changes-detected',
        changedScreenshots: 1,
        changed: [{
          id: 'home-desktop',
          path: '/',
          viewport: 'desktop',
          baselineImagePath: 'baseline.png',
          currentImagePath: 'current.png',
          width: 1440,
          height: 900,
          differentPixels: 500,
          totalPixels: 1296000,
          mismatchRatio: 0.000386,
          status: 'changed'
        }]
      }), { imageReader });

      expect(imageReader).not.toHaveBeenCalled();
      expect(html).not.toContain('data:image/png;base64,');
    });
  });
});
